# Generated by Django 2.1.5 on 2019-02-09 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsndb', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=15)),
                ('subject', models.CharField(choices=[('MTH', 'Math'), ('SCI', 'Science'), ('HIS', 'History'), ('SST', 'Social Studies'), ('CED', 'Computer Education'), ('PHS', 'Physical Education'), ('RDG', 'Reading'), ('WRT', 'Writing'), ('STH', 'Study Hall'), ('SPE', 'Special Education'), ('ENG', 'English'), ('ESL', 'English As a Second Language'), ('ESP', 'Spanish'), ('CHI', 'Chinese'), ('FRN', 'French'), ('GER', 'German'), ('JAP', 'Japanese'), ('LTN', 'Latin'), ('SNL', 'Subject Not Listed')], max_length=3)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsndb.School')),
            ],
        ),
    ]
