# Generated by Django 2.1.5 on 2019-02-09 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsndb', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_datetime', models.DateTimeField()),
                ('calendar_year', models.IntegerField()),
                ('term', models.CharField(choices=[('SPR', 'Spring'), ('SMR', 'Summer'), ('FLL', 'Fall')], max_length=3)),
                ('context', models.TextField(null=True)),
                ('incident_type_program', models.CharField(max_length=50, null=True)),
                ('incident_result_program', models.CharField(max_length=50, null=True)),
                ('incident_type_school', models.CharField(max_length=50, null=True)),
                ('incident_result_school', models.CharField(max_length=50, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsndb.School')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsndb.Student')),
            ],
        ),
    ]
