# Generated by Django 2.1.5 on 2019-02-09 23:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gsndb', '0005_behavior'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('calendar_year', models.IntegerField()),
                ('term', models.CharField(choices=[('SPR', 'Spring'), ('SMR', 'Summer'), ('FLL', 'Fall')], max_length=3)),
                ('grade', models.FloatField()),
                ('final_boolean', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsndb.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsndb.Student')),
            ],
        ),
    ]
