# Generated by Django 2.1.7 on 2019-04-26 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsndb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_set', to='gsndb.School'),
        ),
    ]
