# Generated by Django 2.1.3 on 2018-11-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsndb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='district_number',
        ),
        migrations.AlterField(
            model_name='district',
            name='district_code',
            field=models.CharField(max_length=10),
        ),
    ]
