# Generated by Django 2.1.5 on 2019-02-21 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gsndb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gsndb.Calendar'),
        ),
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gsndb.Course'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gsndb.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gsndb.School'),
        ),
        migrations.AddField(
            model_name='behavior',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gsndb.Calendar'),
        ),
        migrations.AddField(
            model_name='behavior',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gsndb.School'),
        ),
        migrations.AddField(
            model_name='behavior',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gsndb.Student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gsndb.Calendar'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gsndb.School'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gsndb.Student'),
        ),
    ]
