# Generated by Django 2.1.5 on 2019-03-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsndb', '0003_auto_20190326_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birth_date',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='program',
            new_name='current_program',
        ),
    ]
