# Generated by Django 2.1.7 on 2019-03-25 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gsndb', '0003_auto_20190325_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('term', models.CharField(blank=True, choices=[('SPR', 'Spring'), ('SMR', 'Summer'), ('FLL', 'Fall')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MTL', 'Mental Health'), ('DAC', 'Drug & Alcohol/Addictions Counseling'), ('DHS', 'Social Services (Department of Human Services)'), ('YSC', 'Division of Youth Services/Corrections'), ('CPS', 'Childcare/Preschool Services'), ('FMR', 'Family Resources'), ('M/C', 'Meals/Clothing'), ('HOU', 'Housing'), ('SIP', 'Specialized School Intervention Program'), ('TRN', 'Transportation'), ('WFC', 'Work Force Center'), ('IOG', 'Interagency Oversight Group (IOG)'), ('OTH', 'Other')], max_length=3)),
                ('date_given', models.DateField(default=django.utils.timezone.now)),
                ('reference_name', models.CharField(max_length=100, null=True)),
                ('reference_phone', models.BigIntegerField(null=True)),
                ('reference_address', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='avg_daily_attendance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='entry_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendance',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gsndb.School'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gsndb.Student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='term_final_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_exabs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_tardies',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_unexabs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='behavior',
            name='context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='behavior',
            name='incident_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='behavior',
            name='incident_result_program',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='behavior',
            name='incident_result_school',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='behavior',
            name='incident_type_program',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='behavior',
            name='incident_type_school',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='behavior',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gsndb.School'),
        ),
        migrations.AddField(
            model_name='behavior',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gsndb.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(blank=True, choices=[('MTH', 'Math'), ('SCI', 'Science'), ('HIS', 'History'), ('SST', 'Social Studies'), ('CED', 'Computer Education'), ('PHS', 'Physical Education'), ('RDG', 'Reading'), ('WRT', 'Writing'), ('STH', 'Study Hall'), ('SPE', 'Special Education'), ('ENG', 'English'), ('ESL', 'English As a Second Language'), ('ESP', 'Spanish'), ('CHI', 'Chinese'), ('FRN', 'French'), ('GER', 'German'), ('JAP', 'Japanese'), ('LTN', 'Latin'), ('SNL', 'Subject Not Listed')], max_length=3),
        ),
        migrations.AddField(
            model_name='district',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='district',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='district',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2),
        ),
        migrations.AddField(
            model_name='grade',
            name='entry_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gsndb.Student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='term_final_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='current_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gsndb.School'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'NonBinary')], max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_year',
            field=models.SmallIntegerField(choices=[(0, 'Kindergarten'), (1, 'First Grade'), (2, 'Second Grade'), (3, 'Third Grade'), (4, 'Fourth Grade'), (5, 'Fifth Grade'), (6, 'Sixth Grade'), (7, 'Seventh Grade'), (8, 'Eighth Grade'), (9, 'Ninth Grade'), (10, 'Tenth Grade'), (11, 'Eleventh Grade'), (12, 'Twelfth Grade')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(blank=True, choices=[('EA', 'Expelled and At-Risk Student Servies')], max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='reason_in_program',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='state_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gsndb.School'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gsndb.Course'),
        ),
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gsndb.District'),
        ),
        migrations.AddField(
            model_name='referral',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gsndb.Student'),
        ),
        migrations.AddField(
            model_name='referral',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gsndb.Calendar'),
        ),
        migrations.AddField(
            model_name='behavior',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gsndb.Calendar'),
        ),
        migrations.AddField(
            model_name='grade',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gsndb.Calendar'),
        ),
    ]
