# Generated by Django 2.1.7 on 2019-04-26 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsndb', '0003_auto_20190426_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gsndb.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gsndb.School'),
        ),
    ]
