# Generated by Django 2.1.5 on 2019-03-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsndb', '0004_auto_20190327_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='state_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
