# Generated by Django 2.1.7 on 2019-03-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsndb', '0004_auto_20190325_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='state_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
