# Generated by Django 2.1.7 on 2019-05-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsndb', '0002_note'),
        ('gsndb', '0004_auto_20190426_2344'),
    ]

    operations = [
    ]
