# Generated by Django 2.1.7 on 2019-03-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsndb', '0005_auto_20190325_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(blank=True, choices=[('MTH', 'Math'), ('SCI', 'Science'), ('HIS', 'History'), ('SST', 'Social Studies'), ('CED', 'Computer Education'), ('PHS', 'Physical Education'), ('RDG', 'Reading'), ('WRT', 'Writing'), ('STH', 'Study Hall'), ('SPE', 'Special Education'), ('ENG', 'English'), ('ESL', 'English As a Second Language'), ('ESP', 'Spanish'), ('CHI', 'Chinese'), ('FRN', 'French'), ('GER', 'German'), ('JPN', 'Japanese'), ('LTN', 'Latin'), ('SNL', 'Subject Not Listed')], max_length=3),
        ),
    ]
