# Generated by Django 2.1.7 on 2019-05-27 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gsndb', '0005_merge_20190511_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSHA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.CharField(max_length=200)),
                ('hasher', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
