# Generated by Django 2.1.7 on 2019-04-07 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsndb', '0006_auto_20190325_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
        migrations.AddField(
            model_name='behavior',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gsndb.Course'),
        ),
        migrations.AddField(
            model_name='behavior',
            name='period',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='period',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='program',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='gsndb.Program'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='behavior',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gsndb.Program'),
        ),
        migrations.AddField(
            model_name='grade',
            name='program',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='gsndb.Program'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='program',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='gsndb.Program'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='current_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gsndb.Program'),
        ),
    ]
