# Generated by Django 2.2.1 on 2019-06-15 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsndb', '0006_studentuserhasaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_user_has_access', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gsndb.StudentUserHasAccess')),
            ],
        ),
    ]
