# Generated by Django 2.2.1 on 2019-06-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsndb', '0007_mystudents'),
        ('gsndb', '0006_filesha'),
    ]

    operations = [
    ]
