# Generated by Django 2.2.1 on 2019-06-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsndb', '0009_auto_20190626_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_abs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='task',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
