# Generated by Django 2.2.1 on 2019-07-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsndb', '0010_auto_20190626_2145'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historicalstudentid',
            unique_together={('student', 'school', 'student_SISID')},
        ),
    ]
