# Generated by Django 2.2.1 on 2019-07-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsndb', '0013_auto_20190708_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='term',
            field=models.CharField(blank=True, choices=[('SPR', 'Spring'), ('SMR', 'Summer'), ('FLL', 'Fall'), ('Q1', '1st Quarter'), ('Q2', '2nd Quarter'), ('Q3', '3rd Quarter'), ('Q4', '4th Quarter')], max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together={('year', 'term')},
        ),
    ]
